[package]

name = "rust_fst"
version = "0.3.0"
authors = ["Johannes Baiter <johannes.baiter@gmail.com>"]

[lib]
name = "rust_fst"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
fst = "^0.3.0"
fst-levenshtein = "^0.2.0"
fst-regex = "^0.2.0"
